import Script from 'next/script'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GetSummaryHoldings',
  author: 'Jacob Jose'
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-N5DCWKQ06J" />
      <Script src="https://code.jquery.com/jquery-3.6.0.min.js"/>
    </html>
  )
}
